FROM registry.redhat.io/ubi8/ubi:8.5

MAINTAINER dan dan@dan.com

ARG NEXUS_VERSION=2.14.3-02
ENV NEXUS_HOME=/opt/nexus

RUN yum -y --nodocs update && \
    yum -y install java-1.8.0-openjdk-devel && \
    yum -y clean all && \
    groupadd -g 1001 nexus && \
    useradd -u 1001 -g nexus -d ${NEXUS_HOME} -s /sbin/nologin nexus && \
    chmod -R 775 ${NEXUS_HOME}


ADD nexus-2.14.3-02-bundle.tar.gz ${NEXUS_HOME}/
RUN ln -sf ${NEXUS_HOME}/nexus-${NEXUS_VERSION} ${NEXUS_HOME}/nexus2 && \
    chown -R nexus:nexus ${NEXUS_HOME}


USER nexus
WORKDIR ${NEXUS_HOME}

VOLUME /opt/nexus/sonatype-work

CMD ["nexus-start.sh"]

